### ISSUE TITLE
Librarianz Feature Requests (2)

### ISSUE THREAD

**Issue by dhing1024** [demarcod1/librarianz-scripts#31]
Requesting that the following features be considered for addition:

### Restructured Archive Folder ###

The archive folder currently doesn't hold any content. It will be used for the purpose of housing very old chartz. This will mostly include the LSJUMB repository of paper chartz (about 50 years of old music), although this may house some old typeset chartz as well. Important design aspects are:

- **The location of the folder**: Currently, the archives folder exists in a non-obvious part of the drive. A better location would be inside the folder labelled `LSJUMB Full Digitized Chart Data` alongside the `Current Chartz`, `Future Chartz`, and `Old Chartz` folders. This will make it easy to find, and will prevent accidental deletions. This will also make it easier to program into the LSJUMB Digital Music website.
- **Add/Removal Safety**: Currently, any folder that is in the archive folder is delete-safe. In other words, directly deleting a folder will leave the drive in a consistent state, without any lingering broken shortcuts. I would like for the Archive to be add safe as well. If a user directly adds a folder to the drive (given the appropriate folder structure), then later wants to move it into a folder with a different status (e.g. `Old Chartz`), then that will be a safe operation. This may be accomplishable if the archive is designed not to keep track of shortcuts - they are deleted when a song is moved into the archive and recreated when a song moves out of the archive.
- **Addition Via Scripts**: There should be a way to directly add items to the Archives via the scripts. Correct me if this is not true, but currently users are required to upload to the `Old Chartz` (or Current/Future), then move it to the archive afterwards.

### Improved Handling of File/Folder Locating ###

Currently, the Librarianz Scripts utilities parse the Digital Library by checking the directory structure via the folder names. The LSJUMB Digital Music Library Website currently hardcodes a number of Folder IDs into its system. A better way to handle this is to generate a common file, most likely a JSON, that holds the minimal set of Folder IDs (along with the folder's corresponding role in the Drive) needed to function, then using that shared JSON file to inform both the Digital Library web site and the Librarianz Script utility of the directory structure.

The JSON being used in the website would be displayed somewhere in the password-protected area, so that future Librarianz could check to make sure the values are consistent in the event that we need to change drive location. This is certainly a possibility, given that LSJUMB drives are limited to 15 GB and Stanford-owned drives don't appear to have such a limit.

### Support for Miscellaneous Items ###

It is desirable to have a feature that can support Miscellaneous items (e.g. unreleased recordings, fingering chartz, teasers, ARN Licks, arranging resources, parts for unconventional instruments, etc.) that do not fall into the general framework structure of normal chartz. Depending on how much work this would be, it might be better if Librarianz are to manually keep this folder up-to-date, especially since there probably won't be a need to keep shortcuts up-to-date with them.

### Clear Broken Shortcuts Utility ###

In the event that the drive falls into an inconsistent state, one utility that may become useful is a tool that does nothing but clears the drive of any broken shortcuts. This wouldn't be useful in a whole lot of circumstances, but if there are just a few broken shortcuts, this would allow some cleanup without requiring the time commitment needed to run the full remake shortcuts script.

### Error Handling Updates ###

If clean error-handling, as described in #25 hasn't been implemented yet, that should be considered.

**Comment by demarcod1** [comment]
Splitting up into multiple individual issues (to be tackled one-by-one in PRs)
